### ISSUE TITLE
无法自定义服务发现的Ip和Port导致  【服务发现给定的是内网Ip或Docker容器IP】

### ISSUE THREAD

**Issue by MazingAn** [nacos-group/nacos-sdk-csharp#186]
## 在docker环境下或者其他代理网络环境下，无法设置服务发现的真实地址

在docker环境下服务发现地址默认为docker容器的IP和端口而非宿主机的IP和端口，影响分布式部署

解决办法【请求采纳】
设置一个discoverIp 和 discoverPort 的设置，可以在命令行进行特定设置，便于docker-compose下进行服务发布

```docker-compose
services:
  poll1:
    image: poll.v1
    ports:
      - 10041:80/tcp
    container_name: "pollservice1"
    command: "dotnet /app/PollMicroservice.dll --urls=http://*:80 discover:ip=xx.xx.xx.xx discover:port=14001"
    volumes:
      - /config/appsettings.json:/app/appsettings.json

```

**Comment by MazingAn** [comment]
附我的解决办法【修改源代码流程请参考我的blog：https://www.jianshu.com/p/53168dcb8d43】

**Comment by catcherwong** [comment]
现阶段有两种方式解决 docker 的这个问题

1. 就是你说的这个直接指定IP和端口
```json
"nacos": {
    "ServerAddresses": [ "http://localhost:8848" ],  
    "Namespace": "cs", 
    "Ip": "",
    "Port": 0,
//...........
  }
```
2. 指定特定网卡的网段
```json
"nacos": {
    "ServerAddresses": [ "http://localhost:8848" ],  
    "Namespace": "cs", 
    "PreferredNetworks": "", // select an IP that matches the prefix as the service registration IP
//...........
  }
```

**Comment by MazingAn** [comment]
> 

所以，docker-compose可以直接这么些：
```yaml
services:
  poll1:
    image: poll.v1
    ports:
      - 10041:80/tcp
    container_name: "pollservice1"
    command: "dotnet /app/PollMicroservice.dll --urls=http://*:80 nacos:ip=xx.xx.xx.xx nacos:port=14001"
    volumes:
      - /config/appsettings.json:/app/appsettings.json
```
我修改代码的做法纯粹是多此一举了！
