### ISSUE TITLE
will client service automatically unregister itself when it exit?

### ISSUE THREAD

**Issue by li-zheng-hao** [nacos-group/nacos-sdk-csharp#227]
# description
now i deploy my asp.net core webapi service in docker, if i use `docker stop` command to stop my instance, will the instance automatically unregister itself when it exit? or is it just waiting for the nacos server to fail to receive a heartbeat message multiple times to remove this instance?

**Comment by catcherwong** [comment]
> if i use `docker stop` command to stop my instance, will the instance automatically unregister itself when it exit?

Yes! When you execute `docker stop`, your app will call **DeregisterInstance** to deregister the instance.

But if there are irresistible factors, such as power failure, the app can not call **DeregisterInstance** in time, we must wait for the health check mechanism of nacos server to remove this instance.

**Comment by li-zheng-hao** [comment]
No, I just wrote a demo to test it and it doesn't unregister itself actively:

## reproduce steps
1. deploy nacos server use `docker compose`:
```yaml
nacosserver:
    image: nacos/nacos-server:2.0.2
    container_name: nacosserver
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos_conf/nacos_log/:/home/nacos/logs
      - ./nacos_conf/init.d/custom.properties:/home/nacos/init.d/custom.properties
    network_mode: host
```
2. create a webapi project with .net 6 and setttings config is:
```json
"nacos": {
    "ServerAddresses": [ "http://172.10.2.53:8848" ],
    "DefaultTimeOut": 15000,
    "Namespace": "public",
    "ListenInterval": 1000,
    "ServiceName": "Webapi1",
    "GroupName": "DEFAULT_GROUP",
    "ClusterName": "DEFAULT",
    //"Ip": "host.docker.internal",
    //"PreferredNetworks": "172", // select an IP that matches the prefix as the service registration IP
    //"Port": 5000,
    "Weight": 100,
    "RegisterEnabled": true,
    "InstanceEnabled": true,
    "Ephemeral": true,
    "Secure": false,
    "AccessKey": "",
    "SecretKey": "",
    "UserName": "",
    "Password": "",
    "ConfigUseRpc": false,
    "NamingUseRpc": false,
    "NamingLoadCacheAtStart": "",
    "LBStrategy": "WeightRandom", //WeightRandom WeightRoundRobin
    "Metadata": {
      "aa": "bb",
      "cc": "dd"
    }
  }
```
3. build an image and run as container 
4. view nacos server web console ,the service is registered
![1660611921145](https://user-images.githubusercontent.com/22129824/184773129-99a0f159-8431-41ba-a57f-b4b1784d9eed.jpg)
5. use `docker stop` command to stop container 
![image](https://user-images.githubusercontent.com/22129824/184773480-33c0d1bd-89d4-4fc9-b893-d1605bee06f1.png)
6. then, check nacos server web console again, the service is still healthy and change to unhealy and be removed about after 10-30s rather than automatically unregister itself

## more info
- nacos server host: centos7.9
- webapi host: windows 10 and docker desktop 4.9.1 

and i wrote this code to test :
```csharp
IHostApplicationLifetime lifetime = app.Lifetime;
ILogger logger = app.Logger;
lifetime.ApplicationStopping.Register((() =>
{
    logger.LogError("exited");
}));
```
`ApplicationStopping` callback event not be triggered when i use `docker stop`
